---
# tasks file for k8s_master
- name: "Installing docker"
  package:
     name: docker
     state: present
- name: "Starting docker..."
  service:
     name: docker
     state: started
     enabled: true
- name: "Configuring yum for kubeadm"
  yum_repository:
     name: Kubernetes
     description: Repo for kubeadm
     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
     gpgcheck: 1
     gpgkey:
       -  "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
       -  "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
- name: "Installing kubectl, kubelet, kubeadm"
  yum:
     name: "{{ item }}"
     disable_excludes: kubernetes
     state: present
  loop:
  - kubectl
  - kubeadm
  - kubelet
- name: "Enableing kubelet"
  service:
     name: kubelet
     state: started
     enabled: true
- name: "Pulling all the required images"
  shell:
     cmd: "kubeadm config images pull"
- file:
     path: /etc/docker/daemon.js
     state: touch
- name: "Changing docker config"
  blockinfile:
     path: /etc/docker/daemon.js
     block: |
          {
          "exec-opts":["native.cgroupdriver=systemd"]
          }
     state: present
- name: "restarting docker"
  service:
     name: docker
     state: restarted
- name: "Installing iproute-tc"
  package:
     name: iproute-tc
     state: present
- file:
     path: /etc/sysctl.d/k8s.conf
     state: touch
- name: "Configuring ip tables"
  blockinfile:
     path: /etc/sysctl.d/k8s.conf
     block: |
       net.bridge.bridge-nf-call-ip6tables=1
       net.bridge.bridge-nf-call-iptables=1
     state: present
- shell:
     cmd: "sysctl --system"
